---
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: F-Droid - Free and Open Source Android App Repository
header-title: F-Droid
copyright: © 2010-2026 F-Droid Contributors
baseurl: ""  # the subpath of your site, e.g. /fdroid-website
url: "http://localhost:4000"  # the base hostname & protocol for your site

exclude:
  - build
  - public
  - .jekyll-cache
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - tools/
  - README.md
  - LICENSE
  - robots.txt.noindex
  - Vagrantfile
include:
  - "_pages"
  - ".htaccess"
  - ".well-known"
  - "api"
collections:
  tutorials:
    output: true
    permalink: /tutorials/:title/
  docs:
    output: true
    permalink: /docs/:title/
plugins:
  - jekyll-include-cache
  - jekyll-paginate-v2
  - jekyll-redirect-from
  - jekyll-fdroid
fdroid-repo: https://f-droid.org/repo

strict_front_matter: true

# Liquid error handling
error_mode: strict
strict_variables: true
strict_filters: true

pagination:
  enabled: true

# Languages are manually chosen by looking at languages that are fully
# translated across the whole project. Check with this script:
#   ./tools/print-language-status.py
languages: [ar, bo, ca, cs, de, en, es, eu, fa, fr, he, hu, id, is, it, ja, ko, pl, pt, pt_BR, ro, ru, sq, tr, uk, zh_Hans, zh_Hant]
# the languages built and deployed when run with gitlab-ci
gitlab_ci_languages: [en, fa, zh_Hans, zh_Hant]
# Specifying the default language as "_" forces polyglot to generate a
# en/ subdirectory too (with correct links). See
# https://github.com/untra/polyglot/issues/60
default_lang: "_"
# get the lang: front matter from the path, e.g. _pages/zh_Hans/about.md
lang_from_path: true
# exclude these based on what is in the href=""
exclude_from_localization:
  - .htaccess
  - .well-known/
  - CONTRIBUTING.md
  - F-Droid.apk
  - LICENSE
  - README.md
  - TRANSLATIONS.md
  - api/
  - archive/
  - assets/
  - css/
  - feed.xml
  - js/
  - po/
  - repo/
  - robots.txt
  - robots.txt.noindex
  - tools/
  - wiki/
  - wp-content/
  - sitemap.xml
  - funding.json

# name in download link must match name listed in exclude_from_localizations:
fdroid_apk_download_url: https://f-droid.org/F-Droid.apk

fdroid_apk_pgp_verification_instructions_url: docs/Verifying_Downloaded_APK

# App categories
app_categories:
  - App Store & Updater
  - Bookmark
  - Browser
  - Calculator
  - Calendar & Agenda
  - Cloud Storage & File Sync
  - Connectivity
  - DNS & Hosts
  - Development
  - Draw
  - Ebook Reader
  - Email
  - File Encryption & Vault
  - File Transfer
  - Finance Manager
  - Gallery
  - Games
  - Graphics
  - Icon Pack
  - Internet
  - Keyboard & IME
  - Launcher
  - Local Media Player
  - Messaging
  - Money
  - Multimedia
  - Navigation
  - News
  - Note
  - Online Media Player
  - Pass Wallet
  - Password & 2FA
  - Phone & SMS
  - Podcast
  - Public Transport Map & Timetable
  - Reading
  - Recipe Manager
  - Science & Education
  - Security
  - Shopping List
  - Social Network
  - Sports & Health
  - System
  - Task
  - Text Editor
  - Theming
  - Time
  - Translation & Dictionary
  - Unit Convertor
  - VPN & Proxy
  - Voice & Video Chat
  - Wallet
  - Wallpaper
  - Weather
  - Workout
  - Writing

# Set a custom cutmark to separate the excerpt from the rest of the post
excerpt_separator: <!--more-->

# A workaround to fix the CSS
# https://github.com/untra/polyglot/issues/107
sass:
  sourcemap: never
