#!/usr/bin/env python3
#
# For rapid development:
#  while inotifywait -e CLOSE_NOWRITE tools/check-do-not-translate ; do git checkout -- po/*.po*; black --skip-string-normalization tools/check-do-not-translate && tools/check-do-not-translate ; git --no-pager diff -- po/; done

import glob
import os
import re
import yaml


force_dnt = [
    r'''" *[0-9A-F ]{50,}\\n"''',
    r'''"!\[\]\(\{% asset posts/2017-07-03-cuba/be_update1.jpg %\}\)"''',
    r'''"!\[\]\(\{% asset posts/2017-07-03-cuba/fdroid-logo\.png %\}\)"''',
    r'''""\n"    strings:.*?UVODFRYSIHLNWPEJXQZAKCBGMT.*?\$c\\n"''',
    r'''""\n"0\.0\.0\.0 .*?\\n"''',
    r'''""\n"</dt><dd><tt><a href=.*?</a></tt></dd><dt>\\n"''',
    r'''""\n"<p align=\\"center\\">\\n"\n"<a href=\\"https://opencollective.com/f-droid-euro.*?opencollective_button\.png.*?</p>\\n"''',
    r'''""\n"<p align=\\"center\\">\\n"\n"<a href=\\"https://opencollective.com/f-droid/.*?BTC.*?"</a>\\n"\n"</p>\\n"''',
    r'''""\n"Application: The New York Times.*?Google\\n"''',
    r'''""\n"Builds:\\n"\n"  - versionName:.*?v1\.3-fdroid\\n"''',
    r'''""\n"HTTP/1\.1 200 OK\\n"\n"Content-Type: application/json; charset=utf-8\\n"''',
    r'''""\n"\$ sudo apt-get install fdroidserver\\n.*?\\n"''',
    r'''""\n"\* Do not remove this line \(it will not be displayed\)\\n"\n"\{:toc\}\\n"''',
    r'''""\n"\. /etc/profile\\n".*?fdroid build com\.example\\n"''',
    r'''""\n"\|      \| {{ strings.currency }} \| {{ strings.credit_card }}.*?\|\\n"''',
    r'''""\n"android {\\n".*?}\\n"\n"}\\n"''',
    r'''""\n"anti_features:.*?license: Proprietary\\n"''',
    r'''""\n"brew install android-sdk.*?platform-tools.*?\\n"''',
    r'''""\n"gpg --edit-key .*?save\\n"''',
    r'''""\n"id: d25d820d-4c97-420e-a7d7-72434c58a575.*?\\n"''',
    r'''""\n"keytool -genkey.*?-storepass.*?\\n"''',
    r'''""\n"name: Flurry.*?Tracking\\n"''',
    r'''""\n"private fun .*?{.*?}\\n"''',
    r'''""\n"python3 -m venv env\\n"\n"source env/bin/activate\\n"\n"pip install -e \.\\n"''',
    r'''""\n"pyvenv fdroidserver-env.*?gitlab\.com/fdroid/fdroidserver\.git\\n"''',
    r'''""\n"pyvenv fdroidserver-env\\n"\n". fdroidserver-env/bin/activate\\n"\n"pip install git+https://gitlab.com/fdroid/fdroidserver.git\\n"''',
    r'''""\n"sudo add-apt-repository.*?fdroidserver\\n"''',
    r'''""\n"sudo: required\\n.*?  - fdroid nightly -v\\n"''',
    r'''"$ git clone https://gitlab.com/fdroid/fdroid-website\\n"''',
    r'''"<!--more-->\\n"''',
    r'''"</dt><dd><tt><a href=[^\n]+</a></tt></dd></dl>\\n"''',
    r'''"</dt><dd><tt><a href=[^\n]+</a></tt></dd><dt>\\n"''',
    r'''"<div class=\\"payment-methods\\"></div>\\n"''',
    r'''"<dl><dt>\\n"''',
    r'''"<hr \/>\\n"''',
    r'''"<https://[A-Z0-9a-z/.?:=_-]+>"''',
    r'''"<tt>issuebot</tt>"''',
    r'''"\$ echo export ANDROID_HOME=\$ANDROID_HOME >> \.bashrc\\n"''',
    r'''"\$ fdroid rewritemeta --to yml\\n"''',
    r'''"\$ rsync -.+?\\n"''',
    r'''"\[GitHub Sponsors\]\(https://docs.github.com/en/billing/managing-billing-for-github-sponsors/about-billing-for-github-sponsors\)"''',
    r'''"\[Liberapay\]\(https://liberapay.com/about/faq#fees\)"''',
    r'''"\[Open Collective Europe ASBL\]\(https://opencollective.com/europe\)"''',
    r'''"\[Open Source Collective 501\(c\)\(6\)\]\(https://opencollective.com/opensource\)"''',
    r'''"\{% include running-a-mirror-rsync.html %\}"''',
    r'''"`[^`"]+?`"''',
    r'''"apksigner verify --print-certs example.apk | grep SHA-256"''',
    r'''"brew install fdroidserver\\n"''',
    r'''"docker system prune -a\\n"''',
    r'''"echo \"options kvm-intel nested=Y\" > /etc/modprobe.d/kvm-intel.conf\n"''',
    r'''"fdroid build --server -v -l net.artificialworlds.rabbitescape\\n"''',
    r'''"fdroid build org.fdroid.fdroid:16\\n"''',
    r'''"fdroid build\\n"''',
    r'''"fdroid nightly --keystore im.zom.messenger-debug.keystore --show-secret-var\\n"''',
    r'''"fdroid nightly --keystore im.zom.messenger-debug.keystore\\n"''',
    r'''"fdroid publish\\n"''',
    r'''"fdroid rewritemeta org.adaway\\n"''',
    r'''"fdroid rewritemeta\\n"''',
    r'''"fdroid update --help\\n"''',
    r'''"git clone https://gitlab.com/fdroid/fdroiddata.git\\n"''',
    r'''"root:~# cat /proc/cpuinfo\\n"''',
    r'''"root:~# cat /sys/module/kvm_intel/parameters/nested\\n"''',
    r'''"sudo apt-get install fdroidserver\\n"''',
    r'''"sudo apt-get install nginx\\n"''',
    r'''"sudo easy_install fdroidserver\\n"''',
    r'''"vm_provider = 'libvirt'\\n"''',
    r'''"{% assign strings = site.data.strings.sidebars.donate %}"''',
    r'''"‘bzr’"''',
    r'''"‘git-svn’"''',
    r'''"‘git’"''',
    r'''"‘hg’"''',
    r'''"‘srclib’"''',
    r'''"‘svn’"''',
]

# these are allowed to be translated, but default to being copied
default_dnt = [
    r'''" *\*\* *\[[^\(]+\]\([^)]+\) *\*\* *"''',
    r'''"!\[Article Screenshot\]\({% asset posts/2018-12-13-twif-34-f-droid-is-a-planet/izzy_ct_fdroid_article_part_1.jpg %}\)"''',
    r'''"Cygwin"''',
    r'''"Fedora/Archlinux"''',
    r'''"Guix"''',
    r'''"Homebrew:"''',
    r'''"Windows"''',
    r'''"\*\*\[[^\]]+\]\(https://f-droid\.org/packages/[^)]+\)\*\*"''',
    r'''"\[_Bitcoin_\]\(#Bitcoin\)"''',
    r'''"\[_FlattrID_\]\(#FlattrID\)"''',
    r'''"\[_Liberapay_\]\(#Liberapay\)"''',
    r'''"\[_Litecoin_\]\(#Litecoin\)"''',
    r'''"\[_OpenCollective_\]\(#OpenCollective\)"''',
    r'''"_Bitcoin_<a name=\\"Bitcoin\\"></a>"''',
    r'''"_FlattrID_<a name=\\"FlattrID\\"></a>"''',
    r'''"_Liberapay_<a name=\\"Liberapay\\"></a>"''',
    r'''"_Litecoin_<a name=\\"Litecoin\\"></a>"''',
    r'''"_OpenCollective_<a name=\\"OpenCollective\\"></a>"''',
    r'''"macOS"''',
]

patterns = []
for dnt in force_dnt:
    patterns.append(
        re.compile(r'\nmsgid (' + dnt + ')\nmsgstr ".*?"\n\n', flags=re.DOTALL)
    )

# contributor names default to DNT, but won't override translations
with open('_data/contributors.yaml') as fp:
    for c in yaml.safe_load(fp):
        default_dnt.append(c['name'])

for dnt in default_dnt:
    patterns.append(re.compile(r'\nmsgid (' + dnt + ')\nmsgstr ""\n\n'))

os.chdir(os.path.join(os.path.dirname(__file__), '..'))

filelist = []
with open('_config.yml') as fp:
    config = yaml.safe_load(fp)
    for locale in config['languages']:
        for f in glob.glob('po/_*.%s.po' % locale):
            filelist.append(f)

for f in sorted(filelist):
    with open(f) as fp:
        source = fp.read()
    for p in patterns:
        source = p.sub(r'\nmsgid \1\nmsgstr \1\n\n', source)
    with open(f, 'w') as fp:
        fp.write(source)
    print(f)
