#!/bin/sh

basedir=`cd $(dirname $0)/..; pwd`

sed -i 's/^msgstr "[` ]*-----.*"/msgstr ""/' $basedir/po/_*.po*

data=$basedir/_data
# trim trailing whitespace
sed -i 's, *$,,' $data/strings.json $data/*/strings.json \
    $data/tutorials.json $data/*/tutorials.json

perl -i -pe 'BEGIN{undef $/;} s/\nmsgid "<!--more-->.n"\nmsgstr ".*?"/\nmsgid "<!--more-->\\n"\nmsgstr "<!--more-->\\n"/smg' po/_posts.*.po

perl -i -pe 'BEGIN{undef $/;} s/\nmsgid "<hr \/>.n"\nmsgstr ".*?"/\nmsgid "<hr \/>\\n"\nmsgstr "<hr \/>\\n"/smg' po/_posts.*.po

perl -i -pe 'BEGIN{undef $/;} s@\nmsgid "(<https://[A-Z0-9a-z/.?=_-]+>)"\nmsgstr ".*?"@\nmsgid "\1"\nmsgstr "\1"@smg' po/_posts.*.po
