#!/usr/bin/env bash

# Fail on errors.
set -eu -o pipefail

DIR=`dirname $0`
JEKYLL_DIR=${DIR}/../

# The default behaviour is to only include languages where `_data/LANG/strings.json` is 100% translated.
# This can be overriden by "--partial", to include any langugae with at least a single translation.
if [[ $# == 1 && $1 == "--partial" ]]; then
    INCLUDE_PARTIAL=true
else
    INCLUDE_PARTIAL=false
fi

#
# For each directory `_data/[LANG]/ which contains a `strings.json` file, we take LANG and add it to our config file so
# that Jekyll knows to generate a site for that language.
#
function update_langs_in_config {
    LANGS_FOR_YAML='"en"'
    LANGS_FOR_SH='en'

    if [ ${INCLUDE_PARTIAL} == true ]; then
        echo "Including only partially translated languages"
    else
        echo "Consulting Weblate to figure out 100% transtlated languages"
        FULLY_TRANSLATED_LANGS=`get_fully_translated_langs_from_weblate`
    fi

    for I18N_DIR in `find ${JEKYLL_DIR}/_data/*/ -name 'strings.json' -printf '%h\n' | sort -u`; do

        # Check if string contains $LANG already or not: http://stackoverflow.com/a/229606/2391921
        LANG=`basename ${I18N_DIR}`

        # Check the diff between original strings.json and translated one. If no difference, then bail.
        DIFF2=`diff --ignore-all-space ${I18N_DIR}/strings.json ${JEKYLL_DIR}/_data/strings.json | wc -l || true`
        if [ ${DIFF2} == "0" ]; then
            echo "Ignoring completely untranslated ${LANG}/strings.json"
            continue;
        fi

        if [ ${INCLUDE_PARTIAL} == false ]; then
            IN_WEBLATE=`echo ${FULLY_TRANSLATED_LANGS} | grep --only-matching "\<$LANG\>" | wc -l || true`
            if [ ${IN_WEBLATE} == "0" ]; then
                echo "Ignoring not-yet-fully-translated ${LANG}/strings.json"
                continue;
            fi
        fi

        if [[ ${LANGS_FOR_YAML} != *"$LANG"* ]]; then
            LANGS_FOR_YAML="$LANGS_FOR_YAML, \"$LANG\""
            LANGS_FOR_SH="$LANGS_FOR_SH $LANG"
        fi
    done

    if [ ${INCLUDE_PARTIAL} == true ]; then
        for PO in `ls ${JEKYLL_DIR}/po/*.*.po`; do
            PO_FILE=`basename ${PO}`
            LANG=`echo ${PO_FILE} | sed -e "s|.*\.\(.*\)\.po|\1|"`

            # Check the number of messages in the .po file which have been translated. If none, then bail.
            TRANSLATED=`msgattrib --translated ${JEKYLL_DIR}/po/${PO_FILE} | wc -l`
            if [ ${TRANSLATED} == "0" ]; then
                echo "Ignoring completely untranslated $PO_FILE"
                continue;
            fi

            if [[ ${LANGS_FOR_YAML} != *"$LANG"* ]]; then
                LANGS_FOR_YAML="$LANGS_FOR_YAML, \"$LANG\""
                LANGS_FOR_SH="$LANGS_FOR_SH $LANG"
            fi
        done
    fi

    echo "Updating languages to: ${LANGS_FOR_YAML}"
    sed -i "s/^languages: \[.*\]/languages: [ ${LANGS_FOR_YAML} ]/" ${JEKYLL_DIR}/_config.yml

    # This is used by other script which need to know which languages are available.
    cat<<SH > ${JEKYLL_DIR}/.supported-langs
# This file is automatically generated by tools/update_langs.sh
SUPPORTED_LANGS="${LANGS_FOR_SH}"
SH
}

function get_fully_translated_langs_from_weblate {
    # The CSV from Weblate contains the following header row:
    # name,code,total,translated,translated_percent,total_words,translated_words,failing,failing_percent,fuzzy,fuzzy_percent,url_translate,url,last_change,last_author
    # where the columns of interest are $5 (translated_percent) and $2 (code).
    curl --silent https://hosted.weblate.org/exports/stats/f-droid/website/\?format\=csv | \
        tail -n +2 | \
        awk -F ',' '{ if ($5 == "100.0") print $2 }'
}

update_langs_in_config
